export const ActionTypes = {
  RENDER_MAIN_PAGE: 'MAIN_PAGE',
  RENDER_AUTH_PAGE: 'RENDER_AUTH_PAGE',
  RENDER_REG_PAGE: 'RENDER_REG_PAGE',
  RENDER_MOVIE_PAGE: 'RENDER_MOVIE_PAGE',
  RENDER_VIDEO_PAGE: 'RENDER_VIDEO_PAGE',
  RENDER_HEADER: 'RENDER_HEADER',
  GET_USER: 'GET_USER',
  AUTH: 'AUTH',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
};
